### ISSUE TITLE
trouble starting labrad manager

### ISSUE THREAD

**Issue by thetorque** [maffoo/scalabrad#98]
With Win10, starting the batch file with scalabrad 0.8.3 give this error

`14:47:41.552 [main] INFO  org.labrad.manager.Manager$ - registry location: C:\Users\admin\.labrad\registry.sqlite, format=sqlite
14:47:41.677 [main] INFO  org.labrad.crypto.Certs$ - Using saved certificate for host 'HPProDesk01'. certFile=C:\Users\admin\.labrad\manager\certs\HPProDesk01.cert, keyFile=C:\Users\admin\.labrad\manager\keys\HPProDesk01.key
Exception in thread "main" java.lang.IllegalArgumentException: File does not contain valid certificates: C:\Users\admin\.labrad\manager\certs\HPProDesk01.cert
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:246)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:206)
        at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:49)
        at org.labrad.crypto.Certs$.sslContextForHost(Certs.scala:83)
        at org.labrad.manager.Manager$$anonfun$12.apply(Manager.scala:255)
        at org.labrad.manager.Manager$$anonfun$12.apply(Manager.scala:253)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at org.labrad.manager.Manager$.main(Manager.scala:253)
        at org.labrad.manager.Manager.main(Manager.scala)
Caused by: java.security.cert.CertificateParsingException: java.io.IOException: Parse Generalized time, invalid format
        at sun.security.x509.X509CertInfo.<init>(Unknown Source)
        at sun.security.x509.X509CertImpl.parse(Unknown Source)
        at sun.security.x509.X509CertImpl.<init>(Unknown Source)
        at sun.security.provider.X509Factory.engineGenerateCertificate(Unknown Source)
        at java.security.cert.CertificateFactory.generateCertificate(Unknown Source)
        at io.netty.handler.ssl.SslContext.getCertificatesFromBuffers(SslContext.java:990)
        at io.netty.handler.ssl.SslContext.toX509Certificates(SslContext.java:974)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:244)
        ... 13 more
Caused by: java.io.IOException: Parse Generalized time, invalid format
        at sun.security.util.DerInputBuffer.getTime(Unknown Source)
        at sun.security.util.DerInputBuffer.getGeneralizedTime(Unknown Source)
        at sun.security.util.DerInputStream.getGeneralizedTime(Unknown Source)
        at sun.security.x509.CertificateValidity.construct(Unknown Source)
        at sun.security.x509.CertificateValidity.<init>(Unknown Source)
        at sun.security.x509.X509CertInfo.parse(Unknown Source)
        ... 21 more`

Trying with scalabard 0.5.0 gives this error

`14:45:05.945 [main] INFO  org.labrad.manager.Manager$ - registry location: C:\Users\admin\.labrad\registry.sqlite, format=sqlite
14:45:05.949 [main] INFO  org.labrad.manager.Manager$ - Using saved certificate for host 'localhost'. certFile=C:\Users\admin\.labrad\manager\certs\localhost.cert, keyFile=C:\Users\admin\.labrad\manager\keys\localhost.key
Exception in thread "main" javax.net.ssl.SSLException: failed to initialize the server-side SSL context
        at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:222)
        at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:161)
        at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:399)
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:207)
        at org.labrad.manager.Manager$.org$labrad$manager$Manager$$sslContextForHost(Manager.scala:251)
        at org.labrad.manager.Manager$.main(Manager.scala:207)
        at org.labrad.manager.Manager.main(Manager.scala)
Caused by: java.security.cert.CertificateParsingException: java.io.IOException: Parse Generalized time, invalid format
        at sun.security.x509.X509CertInfo.<init>(Unknown Source)
        at sun.security.x509.X509CertImpl.parse(Unknown Source)
        at sun.security.x509.X509CertImpl.<init>(Unknown Source)
        at sun.security.provider.X509Factory.engineGenerateCertificate(Unknown Source)
        at java.security.cert.CertificateFactory.generateCertificate(Unknown Source)
        at io.netty.handler.ssl.SslContext.buildKeyStore(SslContext.java:917)
        at io.netty.handler.ssl.JdkSslContext.buildKeyManagerFactory(JdkSslContext.java:313)
        at io.netty.handler.ssl.JdkSslContext.buildKeyManagerFactory(JdkSslContext.java:291)
        at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:205)
        ... 6 more
Caused by: java.io.IOException: Parse Generalized time, invalid format
        at sun.security.util.DerInputBuffer.getTime(Unknown Source)
        at sun.security.util.DerInputBuffer.getGeneralizedTime(Unknown Source)
        at sun.security.util.DerInputStream.getGeneralizedTime(Unknown Source)
        at sun.security.x509.CertificateValidity.construct(Unknown Source)
        at sun.security.x509.CertificateValidity.<init>(Unknown Source)
        at sun.security.x509.X509CertInfo.parse(Unknown Source)
        ... 15 more`

However, using the 0.3.0 version works.

What's interesting is that I have another machine that runs Win8 and the version 0.8.3 works fine. Any idea?

**Comment by xiaoyuejin** [comment]
I use windows 10 and the version 0.8.3 works just fine. So it is not that.
