### ISSUE TITLE
labrad manager shutting down

### ISSUE THREAD

**Issue by pppplin** [maffoo/scalabrad#99]
Hi,
When I try bin/labrad to start manager, I got the error message on 
some listeners failed to start: java.lang.NullPointerException, java.lang.NullPointerException, any suggestions on how to fix this issue? Thanks.
full error message:
16:23:26.099 [main] INFO  org.labrad.manager.Listener - shutting down
16:23:26.206 [main] INFO  org.labrad.manager.Listener - shutting down
Exception in thread "main" java.lang.Exception: some listeners failed to start: java.lang.NullPointerException, java.lang.NullPointerException
	at org.labrad.manager.Listener.<init>(Listener.scala:114)
	at org.labrad.manager.CentralNode.<init>(Manager.scala:68)
	at org.labrad.manager.Manager$.main(Manager.scala:212)
	at org.labrad.manager.Manager.main(Manager.scala)

**Comment by pppplin** [comment]
More details:
manager connected successfully for the first time, but when I shut it down and try to connect again, the above error occurs. 
Just found that this can be solved by restarting the terminal.
